language: python


python:
  - "3.6"
  - "3.7"

dist: xenial

sudo: false

services:
  - docker

before_install:
  - git clone https://github.com/oceanprotocol/barge
  - cd barge
  - export KEEPER_VERSION=v0.10.3
  - export AQUARIUS_VERSION=v0.3.5
  - rm -rf "${HOME}/.ocean/keeper-contracts/artifacts"
  - bash -x start_ocean.sh --mongodb --no-brizo --no-pleuston --local-spree-node 2>&1 > start_ocean.log &
  - cd ..
  - |
      for i in $(seq 1 50); do
        sleep 5
        [ -f "${HOME}/.ocean/keeper-contracts/artifacts/ready" ] && break
      done
      ls -la "${HOME}/.ocean/keeper-contracts/artifacts/"

install: pip install -U tox-travis

script: tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ${PYPI_USER}
  password: ${PYPI_PASSWORD}
  on:
    tags: true
    repo: oceanprotocol/common-utils-py
    python: 3.6
